/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CarritoRouteImport } from './routes/carrito'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as DesuscribirRouteImport } from './routes/desuscribir'
import { Route as GraciasRouteImport } from './routes/gracias'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminConfiguracionRouteImport } from './routes/admin.configuracion'
import { Route as AdminOrdenesRouteImport } from './routes/admin.ordenes'
import { Route as AdminProductosRouteImport } from './routes/admin.productos'
import { Route as ComboIndexRouteImport } from './routes/combo.$index'
import { Route as ProductoIdRouteImport } from './routes/producto.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CarritoRoute = CarritoRouteImport.update({
  id: '/carrito',
  path: '/carrito',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const DesuscribirRoute = DesuscribirRouteImport.update({
  id: '/desuscribir',
  path: '/desuscribir',
  getParentRoute: () => rootRouteImport,
} as any)
const GraciasRoute = GraciasRouteImport.update({
  id: '/gracias',
  path: '/gracias',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConfiguracionRoute = AdminConfiguracionRouteImport.update({
  id: '/admin/configuracion',
  path: '/admin/configuracion',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdenesRoute = AdminOrdenesRouteImport.update({
  id: '/admin/ordenes',
  path: '/admin/ordenes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductosRoute = AdminProductosRouteImport.update({
  id: '/admin/productos',
  path: '/admin/productos',
  getParentRoute: () => rootRouteImport,
} as any)
const ComboIndexRoute = ComboIndexRouteImport.update({
  id: '/combo/$index',
  path: '/combo/$index',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductoIdRoute = ProductoIdRouteImport.update({
  id: '/producto/$id',
  path: '/producto/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/carrito': typeof CarritoRoute
  '/catalogo': typeof CatalogoRoute
  '/desuscribir': typeof DesuscribirRoute
  '/gracias': typeof GraciasRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/configuracion': typeof AdminConfiguracionRoute
  '/admin/ordenes': typeof AdminOrdenesRoute
  '/admin/productos': typeof AdminProductosRoute
  '/combo/$index': typeof ComboIndexRoute
  '/producto/$id': typeof ProductoIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/carrito': typeof CarritoRoute
  '/catalogo': typeof CatalogoRoute
  '/desuscribir': typeof DesuscribirRoute
  '/gracias': typeof GraciasRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/configuracion': typeof AdminConfiguracionRoute
  '/admin/ordenes': typeof AdminOrdenesRoute
  '/admin/productos': typeof AdminProductosRoute
  '/combo/$index': typeof ComboIndexRoute
  '/producto/$id': typeof ProductoIdRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/carrito': typeof CarritoRoute
  '/catalogo': typeof CatalogoRoute
  '/desuscribir': typeof DesuscribirRoute
  '/gracias': typeof GraciasRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/configuracion': typeof AdminConfiguracionRoute
  '/admin/ordenes': typeof AdminOrdenesRoute
  '/admin/productos': typeof AdminProductosRoute
  '/combo/$index': typeof ComboIndexRoute
  '/producto/$id': typeof ProductoIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/carrito'
    | '/catalogo'
    | '/desuscribir'
    | '/gracias'
    | '/reset-password'
    | '/admin/configuracion'
    | '/admin/ordenes'
    | '/admin/productos'
    | '/combo/$index'
    | '/producto/$id'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/carrito'
    | '/catalogo'
    | '/desuscribir'
    | '/gracias'
    | '/reset-password'
    | '/admin/configuracion'
    | '/admin/ordenes'
    | '/admin/productos'
    | '/combo/$index'
    | '/producto/$id'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/carrito'
    | '/catalogo'
    | '/desuscribir'
    | '/gracias'
    | '/reset-password'
    | '/admin/configuracion'
    | '/admin/ordenes'
    | '/admin/productos'
    | '/combo/$index'
    | '/producto/$id'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CarritoRoute: typeof CarritoRoute
  CatalogoRoute: typeof CatalogoRoute
  DesuscribirRoute: typeof DesuscribirRoute
  GraciasRoute: typeof GraciasRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  AdminConfiguracionRoute: typeof AdminConfiguracionRoute
  AdminOrdenesRoute: typeof AdminOrdenesRoute
  AdminProductosRoute: typeof AdminProductosRoute
  ComboIndexRoute: typeof ComboIndexRoute
  ProductoIdRoute: typeof ProductoIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrito': {
      id: '/carrito'
      path: '/carrito'
      fullPath: '/carrito'
      preLoaderRoute: typeof CarritoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desuscribir': {
      id: '/desuscribir'
      path: '/desuscribir'
      fullPath: '/desuscribir'
      preLoaderRoute: typeof DesuscribirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gracias': {
      id: '/gracias'
      path: '/gracias'
      fullPath: '/gracias'
      preLoaderRoute: typeof GraciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/configuracion': {
      id: '/admin/configuracion'
      path: '/admin/configuracion'
      fullPath: '/admin/configuracion'
      preLoaderRoute: typeof AdminConfiguracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ordenes': {
      id: '/admin/ordenes'
      path: '/admin/ordenes'
      fullPath: '/admin/ordenes'
      preLoaderRoute: typeof AdminOrdenesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/productos': {
      id: '/admin/productos'
      path: '/admin/productos'
      fullPath: '/admin/productos'
      preLoaderRoute: typeof AdminProductosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/combo/$index': {
      id: '/combo/$index'
      path: '/combo/$index'
      fullPath: '/combo/$index'
      preLoaderRoute: typeof ComboIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/producto/$id': {
      id: '/producto/$id'
      path: '/producto/$id'
      fullPath: '/producto/$id'
      preLoaderRoute: typeof ProductoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CarritoRoute: CarritoRoute,
  CatalogoRoute: CatalogoRoute,
  DesuscribirRoute: DesuscribirRoute,
  GraciasRoute: GraciasRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  AdminConfiguracionRoute: AdminConfiguracionRoute,
  AdminOrdenesRoute: AdminOrdenesRoute,
  AdminProductosRoute: AdminProductosRoute,
  ComboIndexRoute: ComboIndexRoute,
  ProductoIdRoute: ProductoIdRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
